/*
 * hw_modulator.c
 *
 *  Created on: Sep 16, 2013
 *      Author: Z Shen
 */
#include "math_const.h"
#include "device.h"
#include "hw_pwm.h"
#include "hw_modulator.h"

/*******************************************************************************
 * Constant derivation
 ******************************************************************************/
#define HW_MOD_PRD			SW_PRD_HALF
#define HW_MOD_MAX_DUTY		PFC_MAX_DUTY
#define HW_MOD_MIN_PW		100e-9
#define HW_MOD_PHASE_BASE	((int)(0.5 * SW_PRD_HALF - PHASE_LOAD_DELAY ))
#define HW_MOD_PHASE_GAIN	(HW_MOD_PRD / PI)
#define HW_MOD_PHASE_LIMIT	(0.3 * PI)
#define HW_MOD_MIN_CMP_CYC	((int)(HW_MOD_MIN_PW * CPU_FREQ / 2))

/*******************************************************************************
 * Public function definition
 ******************************************************************************/
void HW_modulator_pfc(float duty)
{
	#if SW_PER_SAMPLE == 1

	int cmp;
	cmp = (int)(SW_PRD_HALF * __fsat(duty, HW_MOD_MAX_DUTY, -HW_MOD_MAX_DUTY));

	if(cmp == 0) {
		PWM_REGS(AQ_PFC1_LF, 0) = 0x0001;				/* Clear @zero*/
		PWM_REGS(AQ_PFC1_HF, 0) = 0x00D1;				/* Clear @zero, clear @CAU, Toggle@CAD */
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
	}else if (cmp < 0) {
		PWM_REGS(AQ_PFC1_LF, 0) = 0x0002;				/* Set @zero*/
		PWM_REGS(AQ_PFC1_HF, 0) = 0x00D2;				/* Set @zero, Clear @CAU, Toggle@CAD */
		PWM_REGS(CMP_PFC1_HF, 0) = HW_MOD_PRD + cmp;
	}else {
		PWM_REGS(AQ_PFC1_LF, 0) = 0x0001;				/* Clear @zero*/
		PWM_REGS(AQ_PFC1_HF, 0) = 0x00E1;				/* Clear @zero, Set @CAU, Toggle@CAD */
		PWM_REGS(CMP_PFC1_HF, 0) = HW_MOD_PRD - cmp;
	}

	#endif //SW_PER_SAMPLE == 1


	#if SW_PER_SAMPLE == 10
	float duty_sat;
	int n_sw, flag, sign, cmp, cmp0, cmp1, cmpn, AQHF, AQHF0;
	duty_sat =  __fsat(duty, HW_MOD_MAX_DUTY, -HW_MOD_MAX_DUTY);

	cmp = (int)((SW_PRD_HALF * SW_PER_SAMPLE)* duty_sat);

	sign = cmp;
	if (cmp < 0) cmp = -cmp;
	n_sw = cmp / (int)(HW_MOD_MIN_CMP_CYC);
	n_sw = __min(n_sw, SW_PER_SAMPLE);

	if (n_sw == 0) {
		cmpn = 0;
		if (cmp !=0) {
			cmp0 = HW_MOD_PRD - cmp;
			n_sw = 1;
		}
	}else {
		cmp0 = cmp / n_sw;
		cmpn = cmp - cmp0 * n_sw;
		cmp0 = HW_MOD_PRD - cmp0;
		cmp1 = cmp0 - 1;
	}

	flag = (n_sw << 4) | cmpn;

	if(sign == 0) {
//		PWM_REGS(AQ_PFC1_LF, 0) = 0x0001;				/* Clear @zero*/
		PWM_REGS(AQ_PFC1_LF, 0) = 0x0400;				/* Clear @CBD*/
		AQHF0 = 0x00D1;
		AQHF = 0x00D1;
	}else if (sign < 0) {
//		PWM_REGS(AQ_PFC1_LF, 0) = 0x0002;				/* Set @zero*/
		PWM_REGS(AQ_PFC1_LF, 0) = 0x0800;				/* Set @CBD*/
		AQHF0 = 0x00E2;									/* Set @zero, Set @CAU, Toggle@CAD */
		AQHF = 0x00D2;									/* Set @zero, Clear @CAU, Toggle@CAD */
	}else {
//		PWM_REGS(AQ_PFC1_LF, 0) = 0x0001;				/* Clear @zero*/
		PWM_REGS(AQ_PFC1_LF, 0) = 0x0400;				/* Clear @CBD*/
		AQHF0 = 0x00D1;									/* Clear @zero, Clear @CAU, Toggle@CAD */
		AQHF = 0x00E1;									/* Clear @zero, Set @CAU, Toggle@CAD */
	}

	switch (flag) {

	case 0x00:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 1) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 9) = 0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF0;
		break;

	case 0x10:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 1) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 9) = 0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		break;

	case 0x20:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 9) = 0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		break;

	case 0x21:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 9) = 0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		break;

	case 0x30:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 1) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 9) = 0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		break;

	case 0x31:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 1) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 9) = 0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		break;

	case 0x32:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 1) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 9) = 0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		break;

	case 0x40:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 9) = 0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		break;

	case 0x41:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 9) = 0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		break;

	case 0x42:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 9) = 0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		break;

	case 0x43:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 9) = 0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		break;

	case 0x50:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x51:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x52:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x53:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x54:
		PWM_REGS(CMP_PFC1_HF, 0) = 0;
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 4) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x60:
		PWM_REGS(CMP_PFC1_HF, 1) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x61:
		PWM_REGS(CMP_PFC1_HF, 1) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x62:
		PWM_REGS(CMP_PFC1_HF, 1) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x63:
		PWM_REGS(CMP_PFC1_HF, 1) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x64:
		PWM_REGS(CMP_PFC1_HF, 1) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x65:
		PWM_REGS(CMP_PFC1_HF, 1) = 0;
		PWM_REGS(CMP_PFC1_HF, 3) = 0;
		PWM_REGS(CMP_PFC1_HF, 6) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x70:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x71:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x72:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x73:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x74:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x75:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x76:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(CMP_PFC1_HF, 8) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x80:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x81:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x82:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x83:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x84:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x85:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x86:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x87:
		PWM_REGS(CMP_PFC1_HF, 2) = 0;
		PWM_REGS(CMP_PFC1_HF, 7) = 0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;


	case 0x90:
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x91:
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x92:
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x93:
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x94:
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x95:
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x96:
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x97:
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0x98:
		PWM_REGS(CMP_PFC1_HF, 5) = 0;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF0;

		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0xA0:
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0xA1:
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0xA2:
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0xA3:
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0xA4:
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0xA5:
		PWM_REGS(CMP_PFC1_HF, 0) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0xA6:
		PWM_REGS(CMP_PFC1_HF, 1) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0xA7:
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0xA8:
		PWM_REGS(CMP_PFC1_HF, 2) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp0;
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;

	case 0xA9:
		PWM_REGS(CMP_PFC1_HF, 0) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 1) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 2) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 3) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 4) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 6) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 7) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 8) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 9) = cmp1;
		PWM_REGS(CMP_PFC1_HF, 5) = cmp0;
		PWM_REGS(AQ_PFC1_HF, 0) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 1) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 2) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 3) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 4) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 5) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 6) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 7) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 8) = AQHF;
		PWM_REGS(AQ_PFC1_HF, 9) = AQHF;
		break;
	}
	#endif //SW_PER_SAMPLE == 10
}

void HW_modulator_dab(float phase)
{
	#if SW_PER_SAMPLE == 1

	PWM_REGS(PHS_DAB_MAIN, 0) = HW_MOD_PHASE_BASE + (int)(HW_MOD_PHASE_GAIN * __fsat(phase, HW_MOD_PHASE_LIMIT, -HW_MOD_PHASE_LIMIT));

	#endif

	#if SW_PER_SAMPLE > 1

	int ps, ps0, ps1, psn;
	float phase_sat;
	phase_sat = __fsat(phase, HW_MOD_PHASE_LIMIT, -HW_MOD_PHASE_LIMIT);
	ps = (int)((HW_MOD_PHASE_GAIN * SW_PER_SAMPLE) * phase_sat + HW_MOD_PHASE_BASE * SW_PER_SAMPLE);
	ps0 = (int)((HW_MOD_PHASE_GAIN) * phase_sat + HW_MOD_PHASE_BASE);
	psn = ps - (int)(SW_PER_SAMPLE) * ps0;
	if(psn < 0) {
		psn +=10;
		ps0 -= 1;
	}
	ps1 = ps0 + 1;
	#endif

	#if SW_PER_SAMPLE == 10

	switch (psn) {
	default:
	case 0:
		PWM_REGS(PHS_DAB_MAIN, 0)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 1)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 2)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 3)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 4)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 5)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 6)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 7)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 8)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 9)  = ps0;
		break;

	case 1:
		PWM_REGS(PHS_DAB_MAIN, 0)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 1)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 2)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 3)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 4)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 5)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 6)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 7)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 8)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 9)  = ps0;
		break;

	case 2:
		PWM_REGS(PHS_DAB_MAIN, 0)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 1)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 2)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 3)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 4)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 5)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 6)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 7)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 8)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 9)  = ps0;
		break;

	case 3:
		PWM_REGS(PHS_DAB_MAIN, 0)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 1)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 2)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 3)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 4)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 5)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 6)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 7)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 8)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 9)  = ps0;
		break;

	case 4:
		PWM_REGS(PHS_DAB_MAIN, 0)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 1)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 2)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 3)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 4)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 5)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 6)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 7)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 8)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 9)  = ps0;
		break;

	case 5:
		PWM_REGS(PHS_DAB_MAIN, 0)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 1)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 2)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 3)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 4)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 5)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 6)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 7)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 8)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 9)  = ps1;
		break;

	case 6:
		PWM_REGS(PHS_DAB_MAIN, 0)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 1)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 2)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 3)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 4)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 5)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 6)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 7)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 8)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 9)  = ps1;
		break;

	case 7:
		PWM_REGS(PHS_DAB_MAIN, 0)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 1)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 2)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 3)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 4)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 5)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 6)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 7)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 8)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 9)  = ps1;
		break;

	case 8:
		PWM_REGS(PHS_DAB_MAIN, 0)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 1)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 2)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 3)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 4)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 5)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 6)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 7)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 8)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 9)  = ps1;
		break;

	case 9:
		PWM_REGS(PHS_DAB_MAIN, 0)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 1)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 2)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 3)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 4)  = ps0;
		PWM_REGS(PHS_DAB_MAIN, 5)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 6)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 7)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 8)  = ps1;
		PWM_REGS(PHS_DAB_MAIN, 9)  = ps1;
		break;
	}

	#endif //SW_PER_SAMPLE == 10

}
